export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const ADD_USER = "ADD_USER";
export const ADD_USER_FAILURE = "ADD_USER_FAILURE";

export const EDIT_USER = "EDIT_USER";
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";
